FROM node:14
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
COPY ["bundles-src", "./"]

RUN npm install --save-dev parcel
RUN npm ci


CMD ["./node_modules/.bin/parcel", "build", "bundles-src/index.js", "--dist-dir", "bundle", "--public-url='./'"]
