version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=star
      - POSTGRES_PASSWORD=qazwsx
      - POSTGRES_DB=postgres

  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./bundles:/app/bundles
      - ./media:/app/media
      - ./staticfiles:/app/static
#    command: python manage.py collectstatic --noinput
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
#    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - ./bundles:/app/bundles
    depends_on:
      - db

#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: ./Dockerfile.nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - web

volumes:
  postgres_data:
  static:


