version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=star
      - POSTGRES_PASSWORD=qazwsx
      - POSTGRES_DB=postgres

  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bundles:/app/bundles/
      - ./media:/app/media/
      - ./staticfiles:/app/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  postgres_data:

