version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    ports:
      - "8000:8000"
#    volumes:
#      - ./:/usr/src/app/
#      - ./bundles:/usr/src/app/bundles/
#      - ./media:/usr/src/app/media/
#      - ./staticfiles:/usr/src/app/staticfiles/
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_USER=star
      - POSTGRES_PASSWORD=qazwsx
      - POSTGRES_DB=postgres
volumes:
  postgres_data:


