version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=star
      - POSTGRES_PASSWORD=qazwsx
      - POSTGRES_DB=postgres

  web:
    build:
      dockerfile: Dockerfile.dev
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    volumes:
      - ./bundles:/app/bundles/
      - ./media:/app/media/
      - ./staticfiles:/app/staticfiles/
    expose:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    volumes:
      - ./bundles:/app/bundles
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./media:/app/media/
      - ./staticfiles:/app/staticfiles/
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
  media:


