
FROM python:latest

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ADD ./requirements.txt /app/

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
