# Generated by Django 3.2.15 on 2023-06-12 04:29

from django.db import migrations

from foodcartapp.models import Order


def set_orders_price(apps, schema_editor):
    for order in Order.objects.all():
        for item in order.products.all().iterator():
            item.price = item.product.price
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_orders_price)
    ]


