# Generated by Django 3.2.15 on 2023-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230612_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработан', 'Обработан'), ('Необработан', 'Необработан'), ('Готовится', 'Готовится')], db_index=True, default='Необработан', max_length=15, verbose_name='Статус'),
        ),
    ]
