# Generated by Django 3.2.15 on 2023-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment',
        ),
    ]
