# Generated by Django 3.2.15 on 2023-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230615_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Картой')], db_index=True, max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
